"%dev":

  quarkus:
    http:
      port: 8080
      host: 0.0.0.0
    devservices:
      enabled: false 
    swagger-ui:
      always-include: true
    redis:
      hosts: redis://localhost:6379
      devservices:
        enabled: true